name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    - run: npm test
    - name: Lint Frontend Code
      run: npm run lint
    - name: Check Frontend Code Formatting
      run: npx prettier --check .

  backend-ci:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: ./gradlew build
    - run: ./gradlew test
    - name: Lint Backend Code
      run: ./gradlew checkstyleMain 

  frontend-cd:
    needs: [frontend-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Frontend
      run: echo "Frontend deployment steps go here."

  backend-cd:
    needs: [backend-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Backend
      run: echo "Backend deployment steps go here."
